refactor: complete column definitions and move location
OHDSI/dbt-synthea pull request #100
Opened 2024-11-13 21:22 UTC by lawrenceadams

### Sumamry

This pull request includes significant updates to the `seeds` configuration in the `dbt_project.yml` file and the addition of detailed seed configurations in the `seeds/synthea/_sources.yml` file. The main changes involve enabling the `synthea` schema and adding comprehensive column type definitions for various tables.

Updates to `dbt_project.yml`:

* Removed table schema definitions.

Additions to `seeds/synthea/_sources.yml`:

* Added detailed seed configurations with column type definitions for synthea output.

### Why Bother?

 - Removes ambiguity
 - If using other seed files/larger seed files columns may not be sniffed in their entirety and this will result in errors downstream when an incorrect type (e.g. ZIP looks like a `numeric` type by default - causing issues when doing string parsing)

2024-11-14 02:01 UTC, katy-sadowski requested changes
thanks so much for doing this!  suggested a couple minor fixes.

2024-11-14 02:01 UTC, katy-sadowski commented on seeds/synthea/_sources.yml
> +        AMOUNT: numeric
`float`, for consistency with other dollar amounts?

2024-11-14 02:01 UTC, katy-sadowski commented on seeds/synthea/_sources.yml
> +        OUTSTANDING: numeric
all should be floats - dollar amounts

2024-11-15 04:01 UTC, lawrenceadams commented
Thank you @katy-sadowski !! Some silly mistake from myself...

2024-11-15 22:44 UTC, katy-sadowski approved these changes
All good!  Thank you!!!

2024-11-16 00:27 UTC, merged